-- Insert Classes
INSERT INTO SCHOOL_CLASS (NAME, CLASS_CODE, CLASS_YEAR) VALUES ('History', '12C', 2025);
INSERT INTO SCHOOL_CLASS (NAME, CLASS_CODE, CLASS_YEAR) VALUES ('Biology', '11B', 2025);
INSERT INTO SCHOOL_CLASS (NAME, CLASS_CODE, CLASS_YEAR) VALUES ('Mathematics', '10A', 2025);

-- Insert Professors
INSERT INTO PROFESSOR (NAME, DISCIPLINE_CODE, CODE) VALUES ('John Smith', 'MATH', 'P001');
INSERT INTO PROFESSOR (NAME, DISCIPLINE_CODE, CODE) VALUES ('Alice Johnson', 'PHYS', 'P002');
INSERT INTO PROFESSOR (NAME, DISCIPLINE_CODE, CODE) VALUES ('Robert Brown', 'CHEM', 'P003');
INSERT INTO PROFESSOR (NAME, DISCIPLINE_CODE, CODE) VALUES ('Emily Davis', 'BIO', 'P004');

-- Assign Professors to Classes
INSERT INTO CLASS_PROFESSOR (CLASS_ID, PROFESSOR_ID) VALUES (1, 1);
INSERT INTO CLASS_PROFESSOR (CLASS_ID, PROFESSOR_ID) VALUES (1, 2);
INSERT INTO CLASS_PROFESSOR (CLASS_ID, PROFESSOR_ID) VALUES (2, 3);
INSERT INTO CLASS_PROFESSOR (CLASS_ID, PROFESSOR_ID) VALUES (1, 4);
INSERT INTO CLASS_PROFESSOR (CLASS_ID, PROFESSOR_ID) VALUES (1, 3);
INSERT INTO CLASS_PROFESSOR (CLASS_ID, PROFESSOR_ID) VALUES (2, 1);

-- Insert a bootstrap revision into REVINFO
INSERT INTO REVINFO (REVTSTMP) VALUES (EXTRACT(EPOCH FROM CURRENT_TIMESTAMP) * 1000);

-- For portability, we'll just assume revision 1 if REVINFO was empty

-- Populate
INSERT INTO SCHOOL_CLASS_AUD (ID, REV, REVTYPE, NAME, CLASS_CODE, CLASS_YEAR)
SELECT sc.ID,
       (SELECT MAX(REV) FROM REVINFO),
       0,  -- 0 = ADD
       sc.NAME,
       sc.CLASS_CODE,
       sc.CLASS_YEAR
FROM SCHOOL_CLASS sc;


INSERT INTO PROFESSOR_AUD (ID, REV, REVTYPE, NAME, DISCIPLINE_CODE, CODE)
SELECT p.ID,
       (SELECT MAX(REV) FROM REVINFO),
       0, -- 0 = ADD
       p.NAME,
       p.DISCIPLINE_CODE,
       p.CODE
FROM PROFESSOR p;


INSERT INTO CLASS_PROFESSOR_AUD (CLASS_ID, PROFESSOR_ID, REV, REVTYPE)
SELECT cp.CLASS_ID,
       cp.PROFESSOR_ID,
       (SELECT MAX(REV) FROM REVINFO),
       0 -- 0 = ADD
FROM CLASS_PROFESSOR cp;
