-- Insert Classes
INSERT INTO SCHOOL_CLASS (NAME, CLASS_CODE, CLASS_YEAR) VALUES ('Mathematics A1', '9A', 2025);
INSERT INTO SCHOOL_CLASS (NAME, CLASS_CODE, CLASS_YEAR) VALUES ('Physics B1', '9B', 2025);
INSERT INTO SCHOOL_CLASS (NAME, CLASS_CODE, CLASS_YEAR) VALUES ('Chemistry C1', '9C', 2025);
INSERT INTO SCHOOL_CLASS (NAME, CLASS_CODE, CLASS_YEAR) VALUES ('History H1', '11A', 2025);
INSERT INTO SCHOOL_CLASS (NAME, CLASS_CODE, CLASS_YEAR) VALUES ('Biology B1', '11B', 2025);

-- Insert Professors
INSERT INTO PROFESSOR (NAME, DISCIPLINE_CODE, PROFESSOR_CODE) VALUES ('John Smith', 'MATH', 'P001');
INSERT INTO PROFESSOR (NAME, DISCIPLINE_CODE, PROFESSOR_CODE) VALUES ('Alice Johnson', 'PHYS', 'P002');
INSERT INTO PROFESSOR (NAME, DISCIPLINE_CODE, PROFESSOR_CODE) VALUES ('Robert Brown', 'CHEM', 'P003');
INSERT INTO PROFESSOR (NAME, DISCIPLINE_CODE, PROFESSOR_CODE) VALUES ('Emily Davis', 'BIO', 'P004');

-- Assign Professors to Classes
INSERT INTO CLASS_PROFESSOR (CLASS_ID, PROFESSOR_ID) VALUES (1, 1);
INSERT INTO CLASS_PROFESSOR (CLASS_ID, PROFESSOR_ID) VALUES (1, 2);
INSERT INTO CLASS_PROFESSOR (CLASS_ID, PROFESSOR_ID) VALUES (2, 3);
INSERT INTO CLASS_PROFESSOR (CLASS_ID, PROFESSOR_ID) VALUES (2, 1);
INSERT INTO CLASS_PROFESSOR (CLASS_ID, PROFESSOR_ID) VALUES (3, 4);
INSERT INTO CLASS_PROFESSOR (CLASS_ID, PROFESSOR_ID) VALUES (3, 3);
INSERT INTO CLASS_PROFESSOR (CLASS_ID, PROFESSOR_ID) VALUES (3, 1);
