CREATE TABLE SCHOOL_CLASS (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255),
    CLASS_CODE VARCHAR(50),
    CLASS_YEAR INT NOT NULL
);

CREATE TABLE PROFESSOR (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255),
    DISCIPLINE_CODE VARCHAR(50) NOT NULL,
    PROFESSOR_CODE VARCHAR(50) NOT NULL
);

CREATE TABLE CLASS_PROFESSOR (
    CLASS_ID BIGINT NOT NULL,
    PROFESSOR_ID BIGINT NOT NULL,
    PRIMARY KEY (CLASS_ID, PROFESSOR_ID),
    FOREIGN KEY (CLASS_ID) REFERENCES SCHOOL_CLASS(ID),
    FOREIGN KEY (PROFESSOR_ID) REFERENCES PROFESSOR(ID)
);